package ru.otus.common.entity.orders;

public enum OrderStatus {
    ORDER_CREATED, WAITING_FOR_PAYMENT, ORDER_PAYED, PAYMENT_ERROR, ORDER_REJECTED, ORDER_COLLECTED, STOCK_ERROR, DONE, ORDER_REFUND, ORDER_REFUNDED
}
