version: "3.9"
services:
  postgres:
    container_name: postgres_user_profile
    image: postgres:13.3
    environment:
      POSTGRES_DB: "user_profile"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5434:5432"
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "products:2:1,payment:2:1,delivery:2:1,stock:2:1,mail:2:1"
    depends_on:
      - zookeeper