version: "3.9"
services:
  postgres:
    container_name: postgres_user_auth
    image: postgres:13.3
    environment:
      POSTGRES_DB: "user"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5433:5432"