server:
  port: 8000
management:
  server:
    port: 8082
  endpoint:
    health:
      probes:
        enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus
          - loggers
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true