prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
#grafana:
#  ingress:
#    enabled: true
#    ingressClassName: nginx